// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: postman.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Newspaper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Newspaper) Reset() {
	*x = Newspaper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postman_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Newspaper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Newspaper) ProtoMessage() {}

func (x *Newspaper) ProtoReflect() protoreflect.Message {
	mi := &file_postman_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Newspaper.ProtoReflect.Descriptor instead.
func (*Newspaper) Descriptor() ([]byte, []int) {
	return file_postman_proto_rawDescGZIP(), []int{0}
}

func (x *Newspaper) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Newspaper) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RespNewspaper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseMessage string       `protobuf:"bytes,1,opt,name=responseMessage,proto3" json:"responseMessage,omitempty"`
	Data            []*Newspaper `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *RespNewspaper) Reset() {
	*x = RespNewspaper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postman_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespNewspaper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespNewspaper) ProtoMessage() {}

func (x *RespNewspaper) ProtoReflect() protoreflect.Message {
	mi := &file_postman_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespNewspaper.ProtoReflect.Descriptor instead.
func (*RespNewspaper) Descriptor() ([]byte, []int) {
	return file_postman_proto_rawDescGZIP(), []int{1}
}

func (x *RespNewspaper) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

func (x *RespNewspaper) GetData() []*Newspaper {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_postman_proto protoreflect.FileDescriptor

var file_postman_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x6f, 0x73, 0x74, 0x6d, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x43, 0x0a, 0x09, 0x4e, 0x65, 0x77, 0x73, 0x70, 0x61, 0x70, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x59, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x4e, 0x65, 0x77, 0x73,
	0x70, 0x61, 0x70, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x4e, 0x65, 0x77, 0x73, 0x70, 0x61, 0x70, 0x65, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32,
	0x38, 0x0a, 0x07, 0x50, 0x6f, 0x73, 0x74, 0x6d, 0x61, 0x6e, 0x12, 0x2d, 0x0a, 0x0d, 0x53, 0x65,
	0x6e, 0x64, 0x4e, 0x65, 0x77, 0x73, 0x70, 0x61, 0x70, 0x65, 0x72, 0x12, 0x0a, 0x2e, 0x4e, 0x65,
	0x77, 0x73, 0x70, 0x61, 0x70, 0x65, 0x72, 0x1a, 0x0e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x4e, 0x65,
	0x77, 0x73, 0x70, 0x61, 0x70, 0x65, 0x72, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_postman_proto_rawDescOnce sync.Once
	file_postman_proto_rawDescData = file_postman_proto_rawDesc
)

func file_postman_proto_rawDescGZIP() []byte {
	file_postman_proto_rawDescOnce.Do(func() {
		file_postman_proto_rawDescData = protoimpl.X.CompressGZIP(file_postman_proto_rawDescData)
	})
	return file_postman_proto_rawDescData
}

var file_postman_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_postman_proto_goTypes = []interface{}{
	(*Newspaper)(nil),     // 0: Newspaper
	(*RespNewspaper)(nil), // 1: RespNewspaper
}
var file_postman_proto_depIdxs = []int32{
	0, // 0: RespNewspaper.data:type_name -> Newspaper
	0, // 1: Postman.SendNewspaper:input_type -> Newspaper
	1, // 2: Postman.SendNewspaper:output_type -> RespNewspaper
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_postman_proto_init() }
func file_postman_proto_init() {
	if File_postman_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_postman_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Newspaper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postman_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespNewspaper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_postman_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_postman_proto_goTypes,
		DependencyIndexes: file_postman_proto_depIdxs,
		MessageInfos:      file_postman_proto_msgTypes,
	}.Build()
	File_postman_proto = out.File
	file_postman_proto_rawDesc = nil
	file_postman_proto_goTypes = nil
	file_postman_proto_depIdxs = nil
}
